// Preguntas y respuestas almacenadas como constantes
const preguntasRespuestas = [
  {pregunta: "¿Cuál es la capital de Francia?", respuesta: "La capital de Francia es París."},
  {pregunta: "¿En qué año comenzó la Segunda Guerra Mundial?", respuesta: "La Segunda Guerra Mundial comenzó en 1939."},
  {pregunta: "¿Cuál es el principal componente del aire que respiramos?", respuesta: "El principal componente del aire que respiramos es el nitrógeno."},
  {pregunta: "¿Quién escribió Romeo y Julieta?", respuesta: "Romeo y Julieta fue escrito por William Shakespeare."},
  {pregunta: "¿Cuántos continentes hay en el mundo?", respuesta: "Hay siete continentes en el mundo."},
  {pregunta: "¿Cuál es el río más largo del mundo?", respuesta: "El río más largo del mundo es el río Amazonas."},
  {pregunta: "¿Quién fue el primer presidente de Estados Unidos?", respuesta: "El primer presidente de Estados Unidos fue George Washington."},
  {pregunta: "¿Cuál es el símbolo químico del oro?", respuesta: "El símbolo químico del oro es Au."},
  {pregunta: "¿En qué año el ser humano llegó por primera vez a la Luna?", respuesta: "El ser humano llegó por primera vez a la Luna en 1969."},
  {pregunta: "¿Cuál es el animal terrestre más grande?", respuesta: "El animal terrestre más grande es el elefante africano."},
  {pregunta: "¿Cuál es el componente principal del sistema solar?", respuesta: "El Sol es el componente principal del sistema solar."},
  {pregunta: "¿En qué año se fundó la Organización de las Naciones Unidas (ONU)?", respuesta: "La ONU fue fundada en 1945."},
  {pregunta: "¿Quién pintó la Mona Lisa?", respuesta: "La Mona Lisa fue pintada por Leonardo da Vinci."},
  {pregunta: "¿Cuántos huesos tiene el cuerpo humano?", respuesta: "El cuerpo humano tiene 206 huesos."},
  {pregunta: "¿Cuál es el océano más grande del mundo?", respuesta: "El océano más grande del mundo es el océano Pacífico."},
  {pregunta: "¿Cuál es la fórmula química del agua?", respuesta: "La fórmula química del agua es H₂O."},
  {pregunta: "¿Quién fue el líder de Sudáfrica que luchó contra el apartheid?", respuesta: "Nelson Mandela fue el líder que luchó contra el apartheid en Sudáfrica."},
  {pregunta: "¿Cuál es la capital de Japón?", respuesta: "La capital de Japón es Tokio."},
  {pregunta: "¿Qué planeta es conocido como el planeta rojo?", respuesta: "Marte es conocido como el planeta rojo."},
  {pregunta: "¿Quién escribió Cien años de soledad?", respuesta: "Cien años de soledad fue escrito por Gabriel García Márquez."},
  {pregunta: "¿Cuál es el país más grande del mundo en términos de territorio?", respuesta: "Rusia es el país más grande del mundo."},
  {pregunta: "¿En qué año se firmó la Declaración de Independencia de los Estados Unidos?", respuesta: "La Declaración de Independencia de los Estados Unidos se firmó en 1776."},
  {pregunta: "¿Cuál es la moneda oficial de Japón?", respuesta: "El yen japonés es la moneda oficial de Japón."},
  {pregunta: "¿Cuál es la capital de Australia?", respuesta: "La capital de Australia es Canberra."},
  {pregunta: "¿Quién fue el científico que formuló la teoría de la relatividad?", respuesta: "Albert Einstein formuló la teoría de la relatividad."},
  {pregunta: "¿Cuántos colores tiene el arco iris?", respuesta: "El arco iris tiene siete colores: rojo, naranja, amarillo, verde, azul, añil y violeta."},
  {pregunta: "¿Cuál es la montaña más alta del mundo?", respuesta: "El Monte Everest es la montaña más alta del mundo."},
  {pregunta: "¿Qué elemento químico tiene el símbolo O?", respuesta: "El oxígeno tiene el símbolo O."},
  {pregunta: "¿En qué continente se encuentra el desierto del Sahara?", respuesta: "El desierto del Sahara se encuentra en África."},
  {pregunta: "¿Quién fue el primer ser humano en viajar al espacio?", respuesta: "Yuri Gagarin fue el primer ser humano en viajar al espacio."},
  {pregunta: "¿Cuál es el metal más abundante en la corteza terrestre?", respuesta: "El aluminio es el metal más abundante en la corteza terrestre."},
  {pregunta: "¿En qué año cayó el Muro de Berlín?", respuesta: "El Muro de Berlín cayó in 1989."},
  {pregunta: "¿Cuál es la capital de Canadá?", respuesta: "Ottawa es la capital de Canadá."},
  {pregunta: "¿Quién escribió Don Quijote de la Mancha?", respuesta: "Don Quijote de la Mancha fue escrito por Miguel de Cervantes."},
  {pregunta: "¿Cuál es el metal líquido a temperatura ambiente?", respuesta: "El mercurio es el metal líquido a temperatura ambiente."},
  {pregunta: "¿En qué continente se encuentra la Gran Barrera de Coral?", respuesta: "La Gran Barrera de Coral se encuentra en Australia."},
  {pregunta: "¿Cuál es el país más poblado del mundo?", respuesta: "China es el país más poblado del mundo."},
  {pregunta: "¿Cuántos planetas hay en nuestro sistema solar?", respuesta: "Hay ocho planetas en nuestro sistema solar."},
  {pregunta: "¿Quién fue el fundador de Microsoft?", respuesta: "Bill Gates fue el fundador de Microsoft."},
  {pregunta: "¿Cuál es el período de rotación de la Tierra?", respuesta: "La Tierra completa una rotación sobre su eje en aproximadamente 24 horas."},
  {pregunta: "¿Cuál es el océano más profundo del mundo?", respuesta: "El océano más profundo del mundo es el océano Pacífico."},
  {pregunta: "¿En qué año se firmó la Declaración de Derechos de los Estados Unidos?", respuesta: "La Declaración de Derechos de los Estados Unidos se firmó en 1791."},
  {pregunta: "¿Cuál es el símbolo químico del carbono?", respuesta: "El símbolo químico del carbono es C."},
  {pregunta: "¿Quién fue el líder de la Revolución Cubana?", respuesta: "Fidel Castro fue el líder de la Revolución Cubana."},
  {pregunta: "¿Cuántas cámaras tiene el corazón humano?", respuesta: "El corazón humano tiene cuatro cámaras."},
  {pregunta: "¿Cuál es el país más grande de América del Sur?", respuesta: "Brasil es el país más grande de América del Sur."},
  {pregunta: "¿Quién escribió El Principito?", respuesta: "El Principito fue escrito por Antoine de Saint-Exupéry."},
  {pregunta: "¿En qué año se inauguró el Canal de Panamá?", respuesta: "El Canal de Panamá se inauguró en 1914."},
  {pregunta: "¿Cuál es el proceso mediante el cual las plantas fabrican su propio alimento?", respuesta: "La fotosíntesis es el proceso mediante el cual las plantas fabrican su propio alimento."},
  {pregunta: "¿Cuál es el nombre de la primera mujer que viajó al espacio?", respuesta: "Valentina Tereshkova fue la primera mujer que viajó al espacio."},
  {pregunta: "¿Cuál es el río más largo de África?", respuesta: "El río Nilo es el río más largo de África."},
  {pregunta: "¿En qué año se llevó a cabo la Revolución Rusa?", respuesta: "La Revolución Rusa tuvo lugar en 1917."},
  {pregunta: "¿Cuál es la capital de España?", respuesta: "La capital de España es Madrid."},
  {pregunta: "¿Quién escribió Orgullo y prejuicio?", respuesta: "Orgullo y prejuicio fue escrito por Jane Austen."},
  {pregunta: "¿Cuál es el gas más abundante en la atmósfera terrestre?", respuesta: "El nitrógeno es el gas más abundante en la atmósfera terrestre."},
  {pregunta: "¿En qué año se fundó la Unión Europea?", respuesta: "La Unión Europea fue fundada en 1993."},
  {pregunta: "¿Cuál es el segundo planeta más cercano al Sol?", respuesta: "Venus es el segundo planeta más cercano al Sol."},
  {pregunta: "¿En qué año se llevó a cabo la independencia de India?", respuesta: "La independencia de India se logró en 1947."},
  {pregunta: "¿Cuál es el instrumento musical de viento más grande?", respuesta: "El órgano es el instrumento musical de viento más grande."},
  {pregunta: "¿Quién fue el fundador de Facebook?", respuesta: "Mark Zuckerberg fue el fundador de Facebook."},
  {pregunta: "¿Cuál es el metal más resistente?", respuesta: "El tungsteno es el metal más resistente."},
  {pregunta: "¿En qué año se celebró la primera Copa Mundial de la FIFA?", respuesta: "La primera Copa Mundial de la FIFA se celebró en 1930."},
  {pregunta: "¿Cuál es el instrumento musical más antiguo?", respuesta: "La flauta es uno de los instrumentos musicales más antiguos."},
  {pregunta: "¿Quién escribió El Gran Gatsby?", respuesta: "El Gran Gatsby fue escrito por F. Scott Fitzgerald."},
  {pregunta: "¿Cuántos satélites naturales tiene Marte?", respuesta: "Marte tiene dos satélites naturales, Fobos y Deimos."},
  {pregunta: "¿Cuál es el océano más cálido?", respuesta: "El océano Índico es generalmente considerado el océano más cálido."},
  {pregunta: "¿Quién fue la primera mujer en ganar un Premio Nobel?", respuesta: "Marie Curie fue la primera mujer en ganar un Premio Nobel."},
  {pregunta: "¿Cuál es el país más pequeño de América del Sur?", respuesta: "Surinam es el país más pequeño de América del Sur."},
  {pregunta: "¿Qué elemento químico tiene el símbolo Sn?", respuesta: "El estaño tiene el símbolo Sn."},
  {pregunta: "¿Quién es conocido como el Rey del Pop?", respuesta: "Michael Jackson es conocido como el Rey del Pop."},
  {pregunta: "¿Quién fue el fundador de Apple Inc.?", respuesta: "Steve Jobs fue uno de los fundadores de Apple Inc."},
  {pregunta: "¿Cuál es la velocidad de la luz en el vacío?", respuesta: "La velocidad de la luz en el vacío es aproximadamente 299,792 kilómetros por segundo."},
  {pregunta: "¿En qué año se inauguró la Torre Eiffel?", respuesta: "La Torre Eiffel se inauguró en 1889."},
  {pregunta: "¿Cuál es el desierto más grande del mundo?", respuesta: "El desierto Antártico es considerado el desierto más grande del mundo."},
  {pregunta: "¿Quién fue el primer presidente de México?", respuesta: "Guadalupe Victoria fue el primer presidente de México."},
  {pregunta: "¿En qué año se fundó Google?", respuesta: "Google fue fundada en 1998."},
  {pregunta: "¿Cuántos elementos químicos hay en la tabla periódica?", respuesta: "Actualmente hay 118 elementos químicos en la tabla periódica."},
  {pregunta: "¿Cuál es la montaña más alta de América?", respuesta: "El Aconcagua es la montaña más alta de América."},
  {pregunta: "¿Quién fue el primer ser humano en viajar al espacio dos veces?", respuesta: "Gherman Titov fue el primer ser humano en viajar al espacio dos veces."},
  {pregunta: "¿Cuántas caras tiene un icosaedro?", respuesta: "Un icosaedro tiene 20 caras."},
  {pregunta: "¿En qué año se llevó a cabo la Revolución Industrial?", respuesta: "La Revolución Industrial comenzó en el siglo XVIII, alrededor de 1760."},
  {pregunta: "¿Cuál es el país más pequeño de África?", respuesta: "Seychelles es el país más pequeño de África."},
  {pregunta: "¿Cuál es el metal más abundante en la Tierra?", respuesta: "El aluminio es el metal más abundante en la Tierra."},
  {pregunta: "¿En qué año se fundó la Cruz Roja Internacional?", respuesta: "La Cruz Roja Internacional fue fundada en 1863."},
  {pregunta: "¿Cuál es la capital de Suecia?", respuesta: "Estocolmo es la capital de Suecia."},
  {pregunta: "¿Quién fue el pintor del cuadro La persistencia de la memoria?", respuesta: "Salvador Dalí fue el pintor de La persistencia de la memoria."},
  {pregunta: "¿Cuál es la moneda oficial de Suiza?", respuesta: "El franco suizo es la moneda oficial de Suiza."},
  {pregunta: "¿En qué año se proclamó la Declaración de los Derechos del Hombre y del Ciudadano?", respuesta: "La Declaración de los Derechos del Hombre y del Ciudadano se proclamó en 1789 durante la Revolución Francesa."},
  {pregunta: "¿Cuál es la capital de Irlanda?", respuesta: "Dublín es la capital de Irlanda."},
  {pregunta: "¿Cuál es la flor nacional de Japón?", respuesta: "La flor nacional de Japón es el cerezo en flor (sakura)."},
  {pregunta: "¿En qué año se fundó la Organización Mundial de la Salud (OMS)?", respuesta: "La OMS fue fundada en 1948."},
  {pregunta: "¿Cuántos lados tiene un trapezoid?", respuesta: "Un trapezoid tiene cuatro lados."},
  {pregunta: "¿Cuál es el quinto planeta del sistema solar?", respuesta: "Júpiter es el quinto planeta del sistema solar."},
  {pregunta: "¿Quién escribió 1984?", respuesta: "George Orwell escribió 1984."},
  {pregunta: "¿Cuál es el río más largo de Asia?", respuesta: "El río Yangtsé es el río más largo de Asia."},
  {pregunta: "¿Cuál es la capital de Islandia?", respuesta: "Reikiavik es la capital de Islandia."},
  {pregunta: "¿En qué año se fundó la ciudad de Roma?", respuesta: "La ciudad de Roma fue fundada alrededor del 753 a.C."},
  {pregunta: "¿Cuál es el animal más rápido del mundo?", respuesta: "El guepardo es el animal más rápido del mundo."},
  {pregunta: "¿Quién pintó La última cena?", respuesta: "Leonardo da Vinci pintó La última cena."},
  {pregunta: "¿En qué continente se encuentra la Gran Muralla China?", respuesta: "La Gran Muralla China se encuentra en Asia."},
  {pregunta: "¿Quién fue el presidente de Estados Unidos durante la Guerra Civil?", respuesta: "Abraham Lincoln fue el presidente de Estados Unidos durante la Guerra Civil."},
  {pregunta: "¿Cuál es el símbolo químico del hidrógeno?", respuesta: "El símbolo químico del hidrógeno es H."},
  {pregunta: "¿En qué año se llevó a cabo la Revolución Mexicana?", respuesta: "La Revolución Mexicana tuvo lugar entre 1910 y 1920."},
  {pregunta: "¿Cuál es el plato tradicional de la gastronomía italiana?", respuesta: "La pizza es un plato tradicional de la gastronomía italiana."},
  {pregunta: "¿Quién escribió Hamlet?", respuesta: "Hamlet fue escrito por William Shakespeare."},
  {pregunta: "¿Cuántos lados tiene un heptágono?", respuesta: "Un heptágóno tiene siete lados."},
  {pregunta: "¿Cuál es el océano más pequeño del mundo?", respuesta: "El océano Ártico es el océano más pequeño del mundo."},
  {pregunta: "¿Quién fue el primer emperador de China?", respuesta: "Qin Shi Huang fue el primer emperador de China."},
  {pregunta: "¿Quién fue el primer astronauta en dar una vuelta completa a la Tierra?", respuesta: "Yuri Gagarin fue el primer astronauta en dar una vuelta completa a la Tierra."},
  {pregunta: "¿Cuál es el componente principal del diamante?", respuesta: "El diamante está compuesto principalmente de carbono."},
  {pregunta: "¿Cuál es la montaña más alta fuera del sistema solar?", respuesta: "El Monte Olimpo en Marte es la montaña más alta fuera de la Tierra."},
  {pregunta: "¿Cuál es la capital de Rusia?", respuesta: "La capital de Rusia es Moscú."},
  {pregunta: "¿Cuándo se proclamó la Declaración Universal de Derechos Humanos?", respuesta: "La Declaración Universal de Derechos Humanos se proclamó en 1948."},
  {pregunta: "¿Cuál es el río más largo de América del Norte?", respuesta: "El río Misuri es el río más largo de América del Norte."},
  {pregunta: "¿Quién fue el autor de El Señor de los Anillos?", respuesta: "J.R.R. Tolkien fue el autor de El Señor de los Anillos."},
  {pregunta: "¿Cuál es la capital de Sudáfrica?", respuesta: "La capital de Sudáfrica es Pretoria."},
  {pregunta: "¿Quién descubrió la penicilina?", respuesta: "Alexander Fleming descubrió la penicilina."},
  {pregunta: "¿Cuál es el país más pequeño del mundo?", respuesta: "El Vaticano es el país más pequeño del mundo."},
  {pregunta: "¿Quién fue el líder de la Revolución Rusa?", respuesta: "Vladimir Lenin fue el líder de la Revolución Rusa."},
  {pregunta: "¿En qué continente se encuentra la Ciudad del Cabo?", respuesta: "La Ciudad del Cabo se encuentra en África."},
  {pregunta: "¿Cuál es el período orbital de la Luna alrededor de la Tierra?", respuesta: "La Luna completa su órbita alrededor de la Tierra en aproximadamente 27.3 días."},
  {pregunta: "¿Quién escribió Crimen y castigo?", respuesta: "Crimen y castigo fue escrito por Fyodor Dostoyevsky."},
  {pregunta: "¿Cuál es la capital de China?", respuesta: "La capital de China es Pekín (Beijing)."},
  {pregunta: "¿Cuál es el metal más ligero?", respuesta: "El litio es el metal más ligero."},
  {pregunta: "¿Cuál es el planeta más cercano al Sol?", respuesta: "El planeta más cercano al Sol es Mercurio."},
  {pregunta: "¿Quién es conocido como el padre de la teoría de la relatividad?", respuesta: "El padre de la teoría de la relatividad es Albert Einstein."},
  {pregunta: "¿Cuál es el idioma más hablado en el mundo?", respuesta: "El idioma más hablado en el mundo es el chino mandarín."},
  {pregunta: "¿Quién inventó la bombilla eléctrica?", respuesta: "La bombilla eléctrica fue inventada por Thomas Edison."},
  {pregunta: "¿Qué órgano del cuerpo humano consume más energía?", respuesta: "El órgano del cuerpo humano que consumes más energía es el cerebro."},
  {pregunta: "¿En qué año se lanzó el primer satélite artificial?", respuesta: "El primer satélite artificial, Sputnik 1, fue lanzado en 1957."},
  {pregunta: "¿Cuál es el país con más islas en el mundo?", respuesta: "El país con más islas en el mundo es Suecia."},
  {pregunta: "¿Cuál es el libro más vendido de todos los tiempos?", respuesta: "El libro más vendido de todos los tiempos es la Biblia."},
  {pregunta: "¿Cuál es el animal más rápido del mundo?", respuesta: "El halcón peregrino es el animal más rápido del mundo."},
  {pregunta: "¿Cuál es el país con la mayor cantidad de lagos?", respuesta: "El país con la mayor cantidad de lagos es Canadá."},
  {pregunta: "¿Qué país es conocido como la tierra del sol naciente?", respuesta: "Japón es conocido como la tierra del sol naciente."},
  {pregunta: "¿Quién desarrolló la teoría de la evolución?", respuesta: "La teoría de la evolución fue desarrollada por Charles Darwin."},
  {pregunta: "¿Quién fue el primer hombre en pisar la Luna?", respuesta: "El primer hombre en pisar la Luna fue Neil Armstrong."},
  {pregunta: "¿Cuál es el país más poblado de África?", respuesta: "El país más poblado de África es Nigeria."},
  {pregunta: "¿Qué gas es esencial para la respiración humana?", respuesta: "El gas esencial para la respiración humana es el oxígeno."},
  {pregunta: "¿Cuál es el continente más frío del mundo?", respuesta: "El continente más frío del mundo es la Antártida."},
  {pregunta: "¿Quién escribió La Odisea?", respuesta: "La Odisea fue escrita por Homero."},
  {pregunta: "¿En qué año se descubrió América?", respuesta: "América fue descubierta en 1492."},
  {pregunta: "¿Cuál es el país más grande de África?", respuesta: "El país más grande de África es Argelia."},
  {pregunta: "¿Qué país es conocido por la Torre de Pisa?", respuesta: "Italia es conocida por la Torre de Pisa."},
  {pregunta: "¿Cuál es el animal más grande del océano?", respuesta: "El animal más grande del océano es la ballena azul."},
  {pregunta: "¿Cuál es el lago más grande del mundo?", respuesta: "El lago más grande del mundo es el mar Caspio."},
  {pregunta: "¿Qué país es conocido por el tango?", respuesta: "Argentina es conocida por el tango."},
  {pregunta: "¿Cuál es el desierto más frío del mundo?", respuesta: "El desierto más frío del mundo es el desierto de Gobi."},
  {pregunta: "¿Cuál es el país más grande de América del Norte?", respuesta: "El país más grande de América del Norte es Canadá."},
  {pregunta: "¿Qué elemento químico tiene el símbolo H?", respuesta: "El elemento químico con el símbolo H es el hidrógeno."},
  {pregunta: "¿Cuál es el país más pequeño de Europa?", respuesta: "El país más pequeño de Europa es la Ciudad del Vaticano."},
  {pregunta: "¿Qué país es conocido por la Torre Eiffel?", respuesta: "Francia es conocida por la Torre Eiffel."},
  {pregunta: "¿En qué año se fundó la NASA?", respuesta: "La NASA fue fundada en 1958."},
  {pregunta: "¿Cuál es el país más grande de Oceanía?", respuesta: "El país más grande de Oceanía es Australia."},
  {pregunta: "¿Quién escribió Matar a un ruiseñor?", respuesta: "Matar a un ruiseñor fue escrito por Harper Lee."},
  {pregunta: "¿Cuál es la capital de Egipto?", respuesta: "La capital de Egipto es El Cairo."},
  {pregunta: "¿Quién compuso la Novena Sinfonía?", respuesta: "La Novena Sinfonía fue compuesta por Ludwig van Beethoven."},
  {pregunta: "¿Cuál es el elemento más abundante en el universo?", respuesta: "El elemento más abundante en el universo es el hidrógeno."},
  {pregunta: "¿En qué año se fundó la empresa Apple?", respuesta: "Apple fue fundada en 1976."},
  {pregunta: "¿Cuál es la ciudad más poblada del mundo?", respuesta: "La ciudad más poblada del mundo es Tokio."},
  {pregunta: "¿Quién escribió El viejo y el mar?", respuesta: "El viejo y el mar fue escrito por Ernest Hemingway."},
  {pregunta: "¿Cuál es el deporte más popular del mundo?", respuesta: "El deporte más popular del mundo es el fútbol."},
  {pregunta: "¿En qué año se descubrió la penicilina?", respuesta: "La penicilina fue descubierta en 1928."},
  {pregunta: "¿Cuál es la moneda oficial del Reino Unido?", respuesta: "La moneda oficial del Reino Unido es la libra esterlina."},
  {pregunta: "¿Quién fue el primer ser humano en llegar al Polo Sur?", respuesta: "El primer ser humano en llegar al Polo Sur fue Roald Amundsen."},
  {pregunta: "¿Cuál es el animal nacional de Australia?", respuesta: "El animal nacional de Australia es el canguro."},
  {pregunta: "¿En qué año se fundó Microsoft?", respuesta: "Microsoft fue fundada en 1975."},
  {pregunta: "¿Cuál es el idioma oficial de China?", respuesta: "El idioma oficial de China es el mandarín."},
  {pregunta: "¿Quién pintó El grito?", respuesta: "El grito fue pintado por Edvard Munch."},
  {pregunta: "¿Cuál es el río más caudaloso del mundo?", respuesta: "El río más caudaloso del mundo es el río Amazonas."},
  {pregunta: "¿En qué año se produjo la Revolución Francesa?", respuesta: "La Revolución Francesa comenzó en 1789."},
  {pregunta: "¿Cuál es la capital de Argentina?", respuesta: "La capital de Argentina es Buenos Aires."},
  {pregunta: "¿Quién fue la primera mujer en ganar un Premio Nobel de Literatura?", respuesta: "La primera mujer en ganar un Premio Nobel de Literatura fue Selma Lagerlöf."},
  {pregunta: "¿Cuál es el metal más caro del mundo?", respuesta: "El metal más caro del mundo es el rodio."},
  {pregunta: "¿Cuál es la montaña más alta de África?", respuesta: "La montaña más alta de África es el Kilimanjaro."},
  {pregunta: "¿Quién escribió Los miserables?", respuesta: "Los miserables fue escrito por Victor Hugo."},
  {pregunta: "¿Cuál es el país con mayor esperanza de vida?", respuesta: "Japón es el país con mayor esperanza de vida."},
  {pregunta: "¿En qué año se inventó el teléfono?", respuesta: "El teléfono fue inventado en 1876 por Alexander Graham Bell."},
  {pregunta: "¿Cuál es la capital de India?", respuesta: "La capital de India es Nueva Delhi."},
  {pregunta: "¿Quién fue el primer emperador romano?", respuesta: "El primer emperador romano fue Augusto."},
  {pregunta: "¿Cuál es el lago más profundo del mundo?", respuesta: "El lago más profundo del mundo es el lago Baikal."},
  {pregunta: "¿En qué año se fundó la empresa Amazon?", respuesta: "Amazon fue fundada en 1994."},
  {pregunta: "¿Cuál es el idioma oficial de Egipto?", respuesta: "El idioma oficial de Egipto es el árabe."},
  {pregunta: "¿Quién descubrió América?", respuesta: "América fue descubierta por Cristóbal Colón en 1492."},
  {pregunta: "¿Cuál es el país con mayor biodiversidad del mundo?", respuesta: "Brasil es el país con mayor biodiversidad del mundo."},
  {pregunta: "¿En qué año se firmó el Tratado de Versalles?", respuesta: "El Tratado de Versalles se firmó en 1919."},
  {pregunta: "¿Cuál es la capital de Turquía?", respuesta: "La capital de Turquía es Ankara."},
  {pregunta: "¿Quién escribió Drácula?", respuesta: "Drácula fue escrito por Bram Stoker."},
  {pregunta: "¿Cuál es el mineral más duro de la Tierra?", respuesta: "El mineral más duro de la Tierra es el diamante."},
  {pregunta: "¿En qué año se fundó la empresa Tesla?", respuesta: "Tesla fue fundada en 2003."},
  {pregunta: "¿Quién pintó Las meninas?", respuesta: "Las meninas fue pintado por Diego Velázquez."},
  {pregunta: "¿Cuál es el país con mayor producción de café?", respuesta: "Brasil es el país con mayor producción de café."},
  {pregunta: "¿En qué año se fundó la empresa Netflix?", respuesta: "Netflix fue fundada en 1997."},
  {pregunta: "¿Cuál es la capital de Corea del Sur?", respuesta: "La capital de Corea del Sur es Seúl."},
  {pregunta: "¿Quién fue el primer presidente de Argentina?", respuesta: "El primer presidente de Argentina fue Bernardino Rivadavia."},
  {pregunta: "¿Cuál es el animal más venenoso del mundo?", respuesta: "La medusa avispa de mar es el animal más venenoso del mundo."},
  {pregunta: "¿En qué año se fundó la empresa SpaceX?", respuesta: "SpaceX fue fundada en 2002."},
  {pregunta: "¿Quién escribió El nombre de la rosa?", respuesta: "El nombre de la rosa fue escrito por Umberto Eco."},
  {pregunta: "¿Cuál es el país con mayor extensión de costa?", respuesta: "Canadá es el país con mayor extensión de costa."},
  {pregunta: "¿Cuál es la capital de Nigeria?", respuesta: "La capital de Nigeria es Abuya."},
  {pregunta: "¿Quién fue el primer hombre en escalar el Monte Everest?", respuesta: "El primer hombre en escalar el Monte Everest fue Edmund Hillary."},
  {pregunta: "¿Cuál es el metal más pesado?", respuesta: "El osmio es el metal más pesado."},
  {pregunta: "¿En qué año se fundó la empresa Facebook?", respuesta: "Facebook fue fundada en 2004."},
  {pregunta: "¿Quién pintó El jardín de las delicias?", respuesta: "El jardín de las delicias fue pintado por El Bosco."},
  {pregunta: "¿Cuál es el país con mayor número de volcanes?", respuesta: "Indonesia es el país con mayor número de volcanes."},
  {pregunta: "¿En qué año se fundó la empresa Twitter?", respuesta: "Twitter fue fundada in 2006."},
  {pregunta: "¿Cuál es la capital de Vietnam?", respuesta: "La capital de Vietnam es Hanói."},
  {pregunta: "¿Cuál es el elemento químico más reactivo?", respuesta: "El flúor es el elemento químico más reactivo."},
  {pregunta: "¿En qué año se fundó la empresa Instagram?", respuesta: "Instagram fue fundada en 2010."},
  {pregunta: "¿Quién escribió La metamorfosis?", respuesta: "La metamorfosis fue escrita por Franz Kafka."},
  {pregunta: "¿Cuál es el país con mayor producción de petróleo?", respuesta: "Estados Unidos es el país con mayor producción de petróleo."},
  {pregunta: "¿En qué año se fundó la empresa WhatsApp?", respuesta: "WhatsApp fue fundada en 2009."},
  {pregunta: "¿Cuál es la capital de Perú?", respuesta: "La capital de Perú es Lima."},
  {pregunta: "¿Quién fue el primer rey de España?", respuesta: "El primer rey de España fue Carlos I."},
  {pregunta: "¿Cuál es el animal más inteligente después del humano?", respuesta: "El delfín es considerado el animal más inteligente después del humano."},
  {pregunta: "¿En qué año se fundó la empresa LinkedIn?", respuesta: "LinkedIn fue fundada en 2002."},
  {pregunta: "¿Quién pintó La ronda de noche?", respuesta: "La ronda de noche fue pintada por Rembrandt."},
  {pregunta: "¿Cuál es el país con mayor número de idiomas oficiales?", respuesta: "Sudáfrica es el país con mayor número de idiomas oficiales (11)."},
  {pregunta: "¿En qué año se fundó la empresa Uber?", respuesta: "Uber fue fundada en 2009."},
  {pregunta: "¿Cuál es la capital de Colombia?", respuesta: "La capital de Colombia es Bogotá."},
  {pregunta: "¿Cuál es el planeta con más lunas en el sistema solar?", respuesta: "Júpiter es el planeta con más lunas en el sistema solar."},
  {pregunta: "¿En qué año se fundó la empresa Airbnb?", respuesta: "Airbnb fue fundada en 2008."},
  {pregunta: "¿Quién escribió El retrato de Dorian Gray?", respuesta: "El retrato de Dorian Gray fue escrito por Oscar Wilde."},
  {pregunta: "¿Cuál es el país con mayor producción de oro?", respuesta: "China es el país con mayor producción de oro."},
  {pregunta: "¿En qué año se fundó la empresa Spotify?", respuesta: "Spotify fue fundada en 2006."},
  {pregunta: "¿Cuál es la capital de Chile?", respuesta: "La capital de Chile es Santiago."},
  {pregunta: "¿Quién fue el primer gobernante del Imperio Inca?", respuesta: "El primer gobernante del Imperio Inca fue Manco Cápac."},
  {pregunta: "¿Cuál es el metal más conductor de electricidad?", respuesta: "La plata es el metal más conductor de electricidad."},
  {pregunta: "¿En qué año se fundó la empresa TikTok?", respuesta: "TikTok fue fundada en 2016."},
  {pregunta: "¿Quién pintó El nacimiento de Venus?", respuesta: "El nacimiento de Venus fue pintado por Sandro Botticelli."},
  {pregunta: "¿Cuál es el país con mayor número de patrimonios de la humanidad?", respuesta: "Italia es el país con mayor número de patrimonios de la humanidad."},
  {pregunta: "¿En qué año se fundó la empresa PayPal?", respuesta: "PayPal fue fundada en 1998."},
  {pregunta: "¿Cuál es la capital de Venezuela?", respuesta: "La capital de Venezuela es Caracas."},
  {pregunta: "¿Quién fue el primer filósofo de la historia?", respuesta: "Tales de Mileto es considerado el primer filósofo de la historia."},
  {pregunta: "¿Cuál es el animal con la mordedura más fuerte?", respuesta: "El cocodrilo de agua salada tiene la mordedura más fuerte."},
  {pregunta: "¿En qué año se fundó la empresa Samsung?", respuesta: "Samsung fue fundada en 1938."},
  {pregunta: "¿Cuál es el idioma oficial de Pakistán?", respuesta: "El idioma oficial de Pakistán es el urdu."},
  {pregunta: "¿Quién escribió La divina comedia?", respuesta: "La divina comedia fue escrita por Dante Alighieri."},
  {pregunta: "¿Cuál es el país with mayor producción de plata?", respuesta: "México es el país con mayor producción de plata."},
  {pregunta: "¿En qué año se fundó la empresa Intel?", respuesta: "Intel fue fundada en 1968."},
  {pregunta: "¿Cuál es la capital de Filipinas?", respuesta: "La capital de Filipinas es Manila."},
  {pregunta: "¿Cuál es el árbol más alto del mundo?", respuesta: "El árbol más alto del mundo es la secuoya roja."},
  {pregunta: "¿En qué año se fundó la empresa Dell?", respuesta: "Dell fue fundada en 1984."},
  {pregunta: "¿Cuál es el idioma oficial de Irán?", respuesta: "El idioma oficial de Irán es el persa."},
  {pregunta: "¿Cuál es el país con mayor producción de diamantes?", respuesta: "Rusía es el país con mayor producción de diamantes."},
  {pregunta: "¿En qué año se fundó la empresa HP?", respuesta: "HP fue fundada en 1939."},
  {pregunta: "¿Cuál es la capital de Grecia?", respuesta: "La capital de Grecia es Atenas."},
  {pregunta: "¿Quién fue el primer emperador de Japón?", respuesta: "El primer emperador de Japón fue Jimmu."},
  {pregunta: "¿Cuál es el animal más longevo del mundo?", respuesta: "La almeja de Islandia es el animal más longevo del mundo."},
  {pregunta: "¿En qué año se fundó la empresa IBM?", respuesta: "IBM fue fundada en 1911."},
  {pregunta: "¿Cuál es el idioma oficial de Israel?", respuesta: "El idioma oficial de Israel es el hebreo."},
  {pregunta: "¿Quién escribió Guerra y paz?", respuesta: "Guerra y paz fue escrita por León Tolstói."},
  {pregunta: "¿Cuál es el país con mayor producción de cobre?", respuesta: "Chile es el país con mayor producción de cobre."},
  {pregunta: "¿En qué año se fundó la empresa Sony?", respuesta: "Sony fue fundada en 1946."},
  {pregunta: "¿Cuál es la capital de Portugal?", respuesta: "La capital de Portugal es Lisboa."},
  {pregunta: "¿Quién fue el primer presidente de Francia?", respuesta: "El primer presidente de Francia fue Louis-Napoléon Bonaparte."},
  {pregunta: "¿Cuál es el ave más rápida en vuelo horizontal?", respuesta: "El vencejo real es el ave más rápida en vuelo horizontal."},
  {pregunta: "¿En qué año se fundó la empresa Nokia?", respuesta: "Nokia fue fundada en 1865."},
  {pregunta: "¿Cuál es el idioma oficial de Suecia?", respuesta: "El idioma oficial de Suecia es el sueco."},
  {pregunta: "¿Quién pintó El juicio final?", respuesta: "El juicio final fue pintado por Miguel Ángel."},
  {pregunta: "¿Cuál es el país con mayor producción de trigo?", respuesta: "China es el país con mayor producción de trigo."},
  {pregunta: "¿En qué año se fundó la empresa Motorola?", respuesta: "Motorola fue fundada en 1928."},
  {pregunta: "¿Cuál es la capital de Noruega?", respuesta: "La capital de Noruega es Oslo."},
  {pregunta: "¿Quién fue el primer gobernante del Antiguo Egypto?", respuesta: "El primer gobernante del Antiguo Egipto fue Narmer."},
  {pregunta: "¿Cuál es el insecto más fuerte del mundo?", respuesta: "El escarabajo pelotero es el insecto más fuerte del mundo."},
  {pregunta: "¿En qué año se fundó la empresa LG?", respuesta: "LG fue fundada en 1947."},
  {pregunta: "¿Cuál es el idioma oficial de Finlandia?", respuesta: "Los idiomas oficiales de Finlandia son el finés y el sueco."},
  {pregunta: "¿Quién escribió El conde de Montecristo?", respuesta: "El conde de Montecristo fue escrito por Alexandre Dumas."},
  {pregunta: "¿Cuál es el país con mayor producción de arroz?", respuesta: "China es el país con mayor producción de arroz."},
  {pregunta: "¿En qué año se fundó la empresa Huawei?", respuesta: "Huawei fue fundada en 1987."},
  {pregunta: "¿Cuál es la capital de Dinamarca?", respuesta: "La capital de Dinamarca es Copenhague."},
  {pregunta: "¿Quién fue el primer shogun de Japón?", respuesta: "El primer shogun de Japón fue Minamoto no Yoritomo."},
  {pregunta: "¿Cuál es el mamífero más pequeño del mundo?", respuesta: "La musaraña etrusca es el mamífero más pequeño del mundo."},
  {pregunta: "¿Quién compuso Las cuatro estaciones?", respuesta: "Las cuatro estaciones fue compuesta por Antonio Vivaldi."},
  {pregunta: "¿Cuál es la ciudad conocida como  La Ciudad Eterna ?", respuesta: "Roma es conocida como  La Ciudad Eterna ."},
  {pregunta: "¿En qué año se disolvió la Unión Soviética?", respuesta: "La Unión Soviética se disolvió en 1991."},
  {pregunta: "¿Cuál es el metal más noble?", respuesta: "El oro es considerado el metal más noble."},
  {pregunta: "¿Quién escribió En busca del tiempo perdido?", respuesta: "En busca del tiempo perdido fue escrito por Marcel Proust."},
  {pregunta: "¿Cuál es el país con mayor número de husos horarios?", respuesta: "Francia es el país con mayor número de husos horarios (12)."},
  {pregunta: "¿Quién pintó El beso?", respuesta: " El beso  fue pintado por Gustav Klimt."},
  {pregunta: "¿Cuál es el hueso más largo del cuerpo humano?", respuesta: "El fémur es el hueso más largo del cuerpo humano."},
  {pregunta: "¿En qué año se inventó la World Wide Web?", respuesta: "La World Wide Web fue inventada en 1989 por Tim Berners-Lee."},
  {pregunta: "¿Cuál es la capital de Mongolia?", respuesta: "La capital de Mongolia es Ulán Bator."},
  {pregunta: "¿Quién fue el primer director de cine en ganar un Oscar?", respuesta: "Frank Borzage fue el primer director en ganar un Oscar en 1929."},
  {pregunta: "¿Cuál es el lago más grande de África?", respuesta: "El lago Victoria es el lago más grande de África."},
  {pregunta: "¿Qué planeta tiene los anillos más visibles?", respuesta: "Saturno tiene los anillos más visibles."},
  {pregunta: "¿Quién escribió  El amor en los tiempos del cólera ?", respuesta: " El amor en los tiempos del cólera  fue escrito por Gabriel García Márquez."},
  {pregunta: "¿Cuál es el instrumento nacional de Escocia?", respuesta: "La gaita es el instrumento nacional de Escocia."},
  {pregunta: "¿En qué año se coronó a la Reina Isabel II?", respuesta: "La Reina Isabel II fue coronada en 1953."},
  {pregunta: "¿Cuál es el animal nacional de India?", respuesta: "El tigre es el animal nacional de India."},
  {pregunta: "¿Quién descubrió la circulación de la sangre?", respuesta: "William Harvey descubrió la circulación de la sangre."},
  {pregunta: "¿Cuál es la montaña más alta de América del Norte?", respuesta: "Denali (Monte McKinley) es la montaña más alta de América del Norte."},
  {pregunta: "¿En qué año se fundó la OTAN?", respuesta: "La OTAN fue fundada en 1949."},
  {pregunta: "¿Cuál es la capital de Marruecos?", respuesta: "La capital de Marruecos es Rabat."},
  {pregunta: "¿Quién escribió  La isla del tesoro ?", respuesta: " La isla del tesoro  fue escrito por Robert Louis Stevenson."},
  {pregunta: "¿Qué elemento químico tiene el símbolo K?", respuesta: "El potasio tiene el símbolo K."},
  {pregunta: "¿Quién fue el primer europeo en llegar a China por mar?", respuesta: "Vasco da Gama fue el primer europeo en llegar to China por mar."},
  {pregunta: "¿Cuál es la capital de Uzbekistán?", respuesta: "La capital de Uzbekistán es Taskent."},
  {pregunta: "¿En qué año se abolió la esclavitud en Estados Unidos?", respuesta: "La esclavitud fue abolida en Estados Unidos en 1865."},
  {pregunta: "¿Cuál es el país con mayor producción de vino?", respuesta: "Italia es el país con mayor producción de vino."},
  {pregunta: "¿Quién pintó  Los girasoles ?", respuesta: " Los girasoles  fue pintado por Vincent van Gogh."},
  {pregunta: "¿Cuál es el órgano más grande del cuerpo humano?", respuesta: "La piel es el órgano más grande del cuerpo humano."},
  {pregunta: "¿En qué año se fundó la empresa Disney?", respuesta: "Disney fue fundada en 1923."},
  {pregunta: "¿Cuál es la capital de Estonia?", respuesta: "La capital de Estonia es Tallin."},
  {pregunta: "¿Quién escribió  El guardián entre el centeno ?", respuesta: " El guardián entre el centeno  fue escrito por J.D. Salinger."},
  {pregunta: "¿Cuál es el desierto más grande de Asia?", respuesta: "El desierto de Gobi es el más grande de Asia."},
  {pregunta: "¿Qué planeta tiene la mayor gravedad?", respuesta: "Júpiter tiene la mayor gravedad en el sistema solar."},
  {pregunta: "¿Quién fue el primer hombre en cruzar la Antártida a pie?", respuesta: "Roald Amundsen fue el primero en cruzar la Antártida a pie."},
  {pregunta: "¿Cuál es la capital de Kuwait?", respuesta: "La capital de Kuwait es Kuwait City."},
  {pregunta: "¿En qué año se inventó el telescopio?", respuesta: "El telescopio fue inventado en 1608 por Hans Lippershey."},
  {pregunta: "¿Cuál es el país con mayor número de glaciares?", respuesta: "Canadá es el país con mayor número de glaciares."},
  {pregunta: "¿Quién compuso  La flauta mágica ?", respuesta: " La flauta mágica  fue compuesta por Wolfgang Amadeus Mozart."},
  {pregunta: "¿Cuál es la capital de Nepal?", respuesta: "La capital de Nepal es Katmandú."},
  {pregunta: "¿Quién escribió  Los viajes de Gulliver ?", respuesta: " Los viajes de Gulliver  fue escrito por Jonathan Swift."},
  {pregunta: "¿Cuál es el metal más reflectante?", respuesta: "La plata es el metal más reflectante."},
  {pregunta: "¿En qué año se fundó la FIFA?", respuesta: "La FIFA fue fundada en 1904."},
  {pregunta: "¿Cuál es la capital de Sri Lanka?", respuesta: "La capital de Sri Lanka es Sri Jayawardenepura Kotte."},
  {pregunta: "¿Quién pintó  La lección de anatomía del Dr. Nicolaes Tulp ?", respuesta: "Rembrandt pintó  La lección de anatomía del Dr. Nicolaes Tulp ."},
  {pregunta: "¿Cuál es el animal más venenoso de América?", respuesta: "La rana dorada venenosa es el animal más venenoso de América."},
  {pregunta: "¿En qué año se descubrió la estructura del ADN?", respuesta: "La estructura del ADN fue descubierta en 1953."},
  {pregunta: "¿Cuál es la capital de Jamaica?", respuesta: "La capital de Jamaica es Kingston."},
  {pregunta: "¿Quién fue el primer filósofo en usar el término  átomo ?", respuesta: "Demócrito fue el primer filósofo en usar el término  átomo ."},
  {pregunta: "¿Cuál es el país con mayor producción de cacao?", respuesta: "Costa de Marfil es el mayor productor de cacao."},
  {pregunta: "¿Cuál es la capital de Bulgaria?", respuesta: "La capital de Bulgaria es Sofía."},
  {pregunta: "¿Quién escribió  El proceso ?", respuesta: " El proceso  fue escrito por Franz Kafka."},
  {pregunta: "¿Cuál es el mineral más blando?", respuesta: "El talco es el mineral más blando."},
  {pregunta: "¿Cuál es la capital de Senegal?", respuesta: "La capital de Senegal es Dakar."},
  {pregunta: "¿Quién pintó  La libertad guiando al pueblo ?", respuesta: " La libertad guiando al pueblo  fue pintado por Eugène Delacroix."},
  {pregunta: "¿Cuál es el ave nacional de Estados Unidos?", respuesta: "El águila calva es el ave nacional de Estados Unidos."},
  {pregunta: "¿En qué año se fundó la empresa Adobe?", respuesta: "Adobe fue fundada en 1982."},
  {pregunta: "¿Cuál es la capital de Hungría?", respuesta: "La capital de Hungría es Budapest."},
  {pregunta: "¿Quién escribió  El corazón de las tinieblas ?", respuesta: " El corazón de las tinieblas  fue escrito por Joseph Conrad."},
  {pregunta: "¿Cuál es el metal más utilizado en la industria?", respuesta: "El hierro es el metal más utilizado en la industria."},
  {pregunta: "¿En qué año se fundó la empresa Nintendo?", respuesta: "Nintendo fue fundada en 1889."},
  {pregunta: "¿Cuál es la capital de Malasia?", respuesta: "La capital de Malasia es Kuala Lumpur."},
  {pregunta: "¿Quién fue el primer presidente de India?", respuesta: "Rajendra Prasad fue el primer presidente de India."},
  {pregunta: "¿Cuál es el país con mayor producción de té?", respuesta: "China es el mayor productor de té."},
  {pregunta: "¿En qué año se fundó la empresa Porsche?", respuesta: "Porsche fue fundada en 1931."},
  {pregunta: "¿Cuál es la capital de Angola?", respuesta: "La capital de Angola es Luanda."},
  {pregunta: "¿Quién escribió  El extranjero ?", respuesta: " El extranjero  fue escrito por Albert Camus."},
  {pregunta: "¿Cuál es el elemento más abundante en el cuerpo humano?", respuesta: "El oxígeno es el elemento más abundante en el cuerpo humano."},
  {pregunta: "¿En qué año se fundó la empresa Lamborghini?", respuesta: "Lamborghini fue fundada en 极速快3."},
  {pregunta: "¿Cuál es la capital de Camboya?", respuesta: "La capital de Camboya es Phnom Penh."},
  {pregunta: "¿Quién pintó  El caminante sobre el mar de nubes ?", respuesta: " El caminante sobre el mar de nubes  fue pintado por Caspar David Friedrich."},
  {pregunta: "¿Cuál es el animal más rápido en el agua?", respuesta: "El pez vela es el animal más rápido en el agua."},
  {pregunta: "¿En qué año se fundó la empresa Ferrari?", respuesta: "Ferrari fue fundada en 1939."},
  {pregunta: "¿Cuál es la capital de Bolivia?", respuesta: "La capital de Bolivia es Sucre (constitucional) y La Paz (sede de gobierno)."},
  {pregunta: "¿Quién escribió  El lobo estepario ?", respuesta: " El lobo estepario  fue escrito por Hermann Hesse."},
  {pregunta: "¿Cuál es el país con mayor producción de gas natural?", respuesta: "Estados Unidos es el mayor productor de gas natural."},
  {pregunta: "¿En qué año se fundó la empresa Rolex?", respuesta: "Rolex fue fundada en 1905."},
  {pregunta: "¿Quién compuso  El cascanueces ?", respuesta: " El cascanueces  fue compuesto por Pyotr Ilyich Tchaikovsky."},
  {pregunta: "¿Cuál es el metal más resistente a la corrosión?", respuesta: "El oro es el metal más resistente a la corrosión."},
  {pregunta: "¿En qué año se fundó la empresa Canon?", respuesta: "Canon fue fundada en 1937."},
  {pregunta: "¿Cuál es la capital de Ghana?", respuesta: "La capital de Ghana es Acra."},
  {pregunta: "¿Quién escribió  El fin de la eternidad ?", respuesta: " El fin de la eternidad  fue escrito por Isaac Asimov."},
  {pregunta: "¿Cuál es el país con mayor producción de aluminio?", respuesta: "China es el mayor productor de aluminio."},
  {pregunta: "¿En qué año se fundó la empresa Philips?", respuesta: "Philips fue fundada en 1891."},
  {pregunta: "¿Cuál es la capital de Yemen?", respuesta: "La capital de Yemen es Saná."},
  {pregunta: "¿Quién pintó  La joven de la perla ?", respuesta: " La joven de la perla  fue pintado por Johannes Vermeer."},
  {pregunta: "¿Cuál es el animal con el periodo de gestación más largo?", respuesta: "El elefante tiene el periodo de gestación más largo (22 meses)."},
  {pregunta: "¿En qué año se fundó la empresa Siemens?", respuesta: "Siemens fue fundada en 1847."},
  {pregunta: "¿Cuál es la capital de Letonia?", respuesta: "La capital de Letonia es Riga."},
  {pregunta: "¿Quién escribió  Fahrenheit 451 ?", respuesta: " Fahrenheit 451  fue escrito por Ray Bradbury."},
  {pregunta: "¿Cuál es el país con mayor producción de níquel?", respuesta: "Indonesia es el mayor productor de níquel."},
  {pregunta: "¿En qué año se fundó la empresa Bosch?", respuesta: "Bosch fue fundada en 1886."},
  {pregunta: "¿Quién compuso  Carmen ?", respuesta: " Carmen  fue compuesta por Georges Bizet."},
  {pregunta: "¿Cuál es el metal más utilizado en joyería después del oro?", respuesta: "La plata is el metal más utilizado en joyería después del oro."},
  {pregunta: "¿En qué año se fundó la empresa Michelin?", respuesta: "Michelin fue fundada en 1889."},
  {pregunta: "¿Cuál es la capital de Serbia?", respuesta: "La capital de Serbia es Belgrado."},
  {pregunta: "¿Quién escribió  El hombre invisible ?", respuesta: " El hombre invisible  fue escrito por H.G. Wells."},
  {pregunta: "¿Cuál es el país con mayor producción de uranio?", respuesta: "Kazajistán es el mayor productor de uranio."},
  {pregunta: "¿En qué año se fundó la empresa Nestlé?", respuesta: "Nestlé fue fundada en 1866."},
  {pregunta: "¿Cuál es la capital de Eslovaquia?", respuesta: "La capital de Eslovaquia es Bratislava."},
  {pregunta: "¿Cuál es el animal con el cerebro más grande en proporción a su cuerpo?", respuesta: "La hormiga tiene el cerebro más grande en proporción a su cuerpo."},
  {pregunta: "¿En qué año se fundó la empresa Unilever?", respuesta: "Unilever fue fundada en 1929."},
  {pregunta: "¿Cuál es la capital de Costa Rica?", respuesta: "La capital de Costa Rica es San José."},
  {pregunta: "¿Quién escribió  El mundo de Sofía ?", respuesta: " El mundo de Sofía  fue escrito por Jostein Gaarder."},
  {pregunta: "¿Cuál es el país con mayor producción de platino?", respuesta: "Sudáfrica es el mayor productor de platino."},
  {pregunta: "¿En qué año se fundó la empresa Coca-Cola?", respuesta: "Coca-Cola fue fundada en 1892."},
  {pregunta: "¿Cuál es la capital de Uruguay?", respuesta: "La capital de Uruguay es Montevideo."},
  {pregunta: "¿Quién compuso  La consagración de la primavera ?", respuesta: " La consagración de la primavera  fue compuesta por Igor Stravinsky."},
  {pregunta: "¿Cuál es el metal más utilizado en baterías?", respuesta: "El litio es el metal más utilizado en baterías."},
  {pregunta: "¿En qué año se fundó la empresa Pepsi?", respuesta: "Pepsi fue fundada en 1898."},
  {pregunta: "¿Cuál es la capital de Paraguay?", respuesta: "La capital de Paraguay es Asunción."},
  {pregunta: "¿Quién pintó  El matrimonio Arnolfini ?", respuesta: " El matrimonio Arnolfini  fue pintado por Jan van Eyck."},
  {pregunta: "¿Cuál es el animal con el sentido del olfato más desarrollado?", respuesta: "El oso polar tiene el sentido del olfato más desarrollado."},
  {pregunta: "¿En qué año se fundó la empresa McDonald s?", respuesta: "McDonald s fue fundada en 1940."},
  {pregunta: "¿Cuál es la capital de Ecuador?", respuesta: "La capital de Ecuador es Quito."},
  {pregunta: "¿Quién escribió  El nombre del viento ?", respuesta: " El nombre del viento  fue escrito por Patrick Rothfuss."},
  {pregunta: "¿Cuál es el país con mayor producción de esmeraldas?", respuesta: "Colombia es el mayor productor de esmeraldas."},
  {pregunta: "¿En qué año se fundó la empresa Starbucks?", respuesta: "Starbucks fue fundada en 1971."}
];

module.exports = { preguntasRespuestas };